### ISSUE TITLE
大陆访问还是到了加州的amazon

### ISSUE THREAD

**Issue by marlonfan** [Fgaoxing/Vercel-CDN#1]
一个顶级域名, vercel要求的是a记录解析, 完成后是个组播ip.  解析完成后换成这个仓库提供的cname域名, 发现全部流量到了美国加州, 是我哪里操作步骤的问题么?

**Comment by Fgaoxing** [comment]
确认没有配置CNAME预加载

**Comment by marlonfan** [comment]
我试了www设置好了, 看了下顶级域名直接使用好像有一定限制。 感谢作者~
