### ISSUE TITLE
请问vercel.cdn.yt-blog.top是禁ping吗？

### ISSUE THREAD

**Issue by Asakushen** [Fgaoxing/Vercel-CDN#4]
ping域名发现联通和移动全红，自己的域名cname过去，去ping也是全红，不知道实际访问受不受影响

**Comment by Fgaoxing** [comment]
是的



在 2024-08-14 19:40:11，"Asakushen" ***@***.***> 写道：

ping域名发现联通和移动全红，自己的域名cname过去，去ping也是全红，不知道实际访问受不受影响

**Comment by Asakushen** [comment]
谢谢解答
